version: '3.8'                # Specify the Docker Compose version
services:
  web:                        # Define the web application service
    build: .                    # Build from the Dockerfile in the current directory
    ports:
      - "8000:5000"           # Map port 5000 in the container to 8000 on the host
    develop:                           # Monitor changes on app 
      watch:                           
        - action: sync
          path: .                      # sync to local directory
          target: /code
  redis:                               # Define redis serv
    image: "redis:alpine"              # use Alpine-based Redis image
